#! /bin/bash

scala -cp /usr/local/httpcomponents-client-4.0.1/lib/httpclient-4.0.1.jar:/usr/local/httpcomponents-core-4.0.1/lib/httpcore-4.0.1.jar:/usr/share/java/commons-logging-1.1.1/commons-logging-1.1.1.jar:classes TestDbPos $1
